name: Deploy HTML, JavaScript, CSS, and Images to Azure Web App - uscldv3dwad01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip HTML, JavaScript, CSS, and Images
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: release.zip

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: web-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az webapp deployment source config-zip --resource-group e2v3drgd01 --name 'uscldv3dwad01' --src ./ --slot 'preprod'

          
